### PR TITLE
Linegroup

### PR DESCRIPTION
**Pull request by InternetofAwesome**

### CODE REVIEW

**Comment by Pomax** [comment]
What was this? =)

**Comment by InternetofAwesome** [comment]
Ya, sorry about that.  Clicked too quickly on the PR button, and didn't see
a way to delete it. ><


Regards,
Sam Anderson
918-527-4421
SamsURL.com
linkedin.com/in/samcanderson <http://www.linkedin.com/in/samcanderson/>

**Comment by Pomax** [comment]
No really though, what was this? Personal project PR'd to the wrong repo? What did you use bezier.js for? =)

**Comment by InternetofAwesome** [comment]
Heh, sorry, wasn't being intentionally vague.
I am making a tool for creating LED animation profiles using bezier
curves.  I am a firmware engineer, and industrial designers tend to pick
some of the least effective ways to communicate to FW engineers what they
want the LEDs to do, so I am making a tool to help bridge that gap.

Regards,
Sam Anderson
918-527-4421
SamsURL.com
linkedin.com/in/samcanderson <http://www.linkedin.com/in/samcanderson/>

**Comment by Pomax** [comment]
oh cool. A full bezier.js might be overkill, but I guess following the "make it work, *then* make it fast/tiny/etc" adage that's not really a concern yet =)

**Comment by InternetofAwesome** [comment]
Ya, definitely focusing on functionality first. This will probably never be
something that needs to be terribly polished either. Main reason for going
with bezier.js was that it is interactive, in browser, and has a lot of the
utility functions for manipulating splines that I needed. Not using server
side code at all for what I am doing.

Regards,
Sam Anderson
918-527-4421
SamsURL.com
linkedin.com/in/samcanderson <http://www.linkedin.com/in/samcanderson/>

**Comment by Pomax** [comment]
yeah fair enough. If it helps get a prototype up in less time it'd otherwise take, I'd say the library alway won =)

**Pull request closed without merging**
