### PR TITLE
Fix CommonJS module loaded as ECMAScript module

### PR DESCRIPTION
**Pull request by aidant**
When using require to load `bezier-js@4.0.3` from node version 12.14.1 we get the following warning in our application:

```
(node:1292) Warning: require() of ES modules is not supported.
require() of node_modules/bezier-js/dist/bezier.common.js from <application> is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename bezier.common.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from node_modules/bezier-js/package.json.
```

### CODE REVIEW

**Comment by Pomax** [comment]
I would honestly recommend first try moving up to Node 14 LTS instead, rather than trying to accommodate a legacy pattern. Node 14 was a drastic upgrade in terms of Node supporting the modern JS language and feature set, and 12 is in pure "security fixes only" mode now, so even ignoring esmodules, 12 will simply never support what is now basic JS syntax like the `??` operator etc.

**Comment by aidant** [comment]
Normally I would agree with you, however, we are stuck with Node 12 due to an older version of Electron we need to support in our application.

**Comment by Pomax** [comment]
Hm, but Electron works just fine one new versions of node, and should be fully backward compatible?

**Comment by aidant** [comment]
Node does actually look at nearby `package.json` files in the new module resolution which is why this fix is important, see the node docs on [Determining Module System](https://nodejs.org/dist/latest/docs/api/packages.html#packages_determining_module_system).

> Files ending in .js when the nearest parent package.json file contains a top-level "type" field with a value of "module".

So by changing the file extension to `.cjs` we would be forcing node to treat the transpiled CommonJS version as a CommonJS module rather than the `package.json`s type which specifies an ECMAScript module.

**Comment by Pomax** [comment]
Hm, but those docs don't mention what happens with `require`, which seems a glaring omission. What I want to avoid is putting in a fix that is only a fix for the legacy Node 12. Does Node 14 also complain in the same way, when using the same code (`nvm` should make testing that pretty straight forward)? If so, then sure let's change it.

**Comment by aidant** [comment]
Interesting thing to note, in node 12.17.0 and above including node 14 there is a new issue in which node ignores the `main` field in the `package json` when using `require`, see the following error:

```
internal/modules/cjs/loader.js:1154
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: node_modules/bezier-js/src/bezier.js
require() of ES modules is not supported.
require() of node_modules/bezier-js/src/bezier.js from <application> is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename bezier.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from node_modules/bezier-js/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1154:13)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (<application>)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14) {
  code: 'ERR_REQUIRE_ESM'
}

```

Looking at the node docs on the ["main"](https://nodejs.org/dist/latest/docs/api/packages.html#packages_main) field:

> When a package has an "exports" field, this will take precedence over the "main" field when importing the package by name.

I'll do a bit more digging and fix this issue now.

**Comment by aidant** [comment]
I've added [Conditional Exports](https://nodejs.org/dist/latest/docs/api/packages.html#packages_conditional_exports) to support the [Dual CommonJS/ECMAScript package](https://nodejs.org/dist/latest/docs/api/packages.html#packages_dual_commonjs_es_module_packages) configuration. I've tested both `require` and `import` against a range of node versions with and without this fix, see the results bellow:

`npm i bezier-js@4.0.3`
| Node Version | Require Supported      | Import Supported                    |
| ------------ | ---------------------- | ----------------------------------- |
| v12.0.0      | Yes                    | No <sup>Experimental Flag</sup>     |
| v12.14.1     | Yes <sup>Warning</sup> | Yes <sup>Experimental Flag</sup>    |
| v12.17.0     | No                     | Yes <sup>Experimental Warning</sup> |
| v12.22.1     | No                     | Yes                                 |
| v14.0.0      | No                     | Yes                                 |
| v14.16.1     | No                     | Yes                                 |


`npm i grumpysailor/bezierjs#fix/commonjs`
| Node Version | Require Supported | Import Supported                    |
| ------------ | ----------------- | ----------------------------------- |
| v12.0.0      | Yes               | Yes <sup>Experimental Flag</sup>    |
| v12.14.1     | Yes               | No <sup>Experimental Flag</sup>     |
| v12.17.0     | Yes               | Yes <sup>Experimental Warning</sup> |
| v12.22.1     | Yes               | Yes                                 |
| v14.0.0      | Yes               | Yes                                 |
| v14.16.1     | Yes               | Yes                                 |

This now allows both newer and older versions of node (ignoring experimental) to either `require` or `import` this package.

Note: node does advise that packages in this configuration isolate state out into a shared module between the CommonJS and ECMAScript module, see [Approach #2 Isolate State](https://nodejs.org/dist/latest/docs/api/packages.html#packages_approach_2_isolate_state) to my understanding this is not an issue in this package since this is a stateless package?

**Comment by Pomax** [comment]
That's some solid experimentation  - want to add that second support matrix to the README as part of the PR, too? I can merge it after, and then release a new minor version

**Comment by aidant** [comment]
Cool all done! Wasn't sure where the best spot to add it was, feel free to change it as you see fit.

**Review by Pomax — APPROVED** [review]

**Comment by Pomax** [comment]
v4.1.0 published

**Pull request merged**
