### PR TITLE
WIP: FP version of Bezier.js

### PR DESCRIPTION
**Pull request by louisremi**
Our Functional Programing version of Bezier.js is now stable enough for us to start discussing how it could be merged into your official repo.

## Why did we do this?

The current core of [Prototypo](https://www.prototypo.io) is built on top of Paper.js' stateful and object-oriented API, but the UI is built with stateless and functional (as in [FP](https://en.wikipedia.org/wiki/Functional_programming)) React components. We have important performance constraints so we have started parallelizing work by moving the core of the app to a WebWorker.

Using Paper.js with React has proven painful, and we know that, should we want to parallelize the work to several WebWorkers, synchronizing states across them would only make things worse. To simplify our code-base and pave the way for more parallelism in the app, we have made a mid-term goal of switching to a stateless core. Building a stateless version of Paper.js isn't an option for now, but this appeared feasible with Bezier.js, and its API is rich enough for us.

## How is it different / similar?

1. In Bezier.fp.js, there is no `Bezier()` constructor. A bezier curve is represented as an `Array` of points, exactly like the `.points` property of Bezier.js instances: `[{x:0,y:0}, {x:1,y:1}, ... {x:n,y:n}]`
2. All Bezier instance methods have counterparts directly on the `Bezier` object. Their first argument is always a `curve` (an `Array` of points), the rest of the signature is the same.
3. The exception to the previous rule is `.update`, as it's no longer needed (see below).
4. All of those counterparts are pure functions: they never mutate the arguments they receive.
5. There are no `.order`, `.dims`, `.dimlen`, `.dpoints`, `.clockwise` or similar properties. Instead, we've provided functions directly on the `Bezier` object to calculate them when they're needed.
6. There are three exceptions to the previous rule for `._t1`, `._t2` and `.virtual` properties. Those properties aren't used most of the time, so we decided that, if they were needed, they should appear as properties of the first point of the curve. This isn't ideal, but we considered two alternatives that didn't appear better:
    - as one of the main objectives of Bezier.fp.js is performance, we need data-structures that are as flat as possible, so that it is as efficient as possible to convert from any data-model to it, and back. This is why we don't want to wrap the `Array` of points in another `Object`.
    - we know we could still set properties on the `Array`, but we consider this a bad practice. They would be far less obvious when trying to debug the code, and there are many ways to loose those properties while copying the objects (something pure functions do a lot).
7. We re-wrote many functions from utils.js to account for the new data structure, and to make all those functions pure as well.

## What should be discussed

1. We want to make sure that all the decisions we've taken so far make sense to you :-)
2. ~~We need to discuss how those two different libs should be distributed. We propose having two different npm packages for the two different versions, both hosted in this very repo. This cohabitation would be managed using [Lerna](https://github.com/lerna/lerna).~~
3. For now, we've mostly duplicated code from bezier.js and utils.js to their FP counterparts. It could be possible to factorize some code ~~into a third npm package~~.
4. How and where the FP version should be documented.

Thank you for your time, and thank you again for your awesome work on Bezier.js!

### CODE REVIEW

**Comment by Pomax** [comment]
Remark about the first point 5: the whole reason those values exist is because you *don't* want to run functions that recompute invariant values. If the curve does not change, that set of values does not change, so a practical implementation computes them only once (which can be done JIT of course), and then never "computes" them on subsequent calls, returning the cached values, invalidating the cache when the curve points change.

**Comment by Pomax** [comment]
Distribution-wise, there is no reason to rely on lerna: the FP version can live in its own `fp` dir, and code that needs it can just `require('bezierjs/fp')` - directory structure is preserved regardless of whether a commonjs2 import is done "from file" or from the module repository.

**Comment by louisremi** [comment]
Thank you for taking the time to answer!

> If the curve does not change, that set of values does not change, so a practical implementation computes them only once (which can be done JIT of course), and then never "computes" them on subsequent calls, returning the cached values, invalidating the cache when the curve points change.

This is exactly why Bezier.fp.js exists: its a set of pure functions meant to be used with a memoizing library such as [memoize-immutable](https://github.com/louisremi/memoize-immutable). This will likely appear in the documentation, as it allows writing code that is simpler than the OOP lib (there's no need to remember to call `#update()` after modifying the curve), and equally efficient.

> Distribution-wise, there is no reason to rely on lerna: the FP version can live in its own fp dir, and code that needs it can just require('bezierjs/fp') - directory structure is preserved regardless of whether a commonjs2 import is done "from file" or from the module repository.

I wasn't sure about that, but that sounds perfect.

**Comment by louisremi** [comment]
I've moved my files to an /fp subdir.

**Pull request closed without merging**
