### PR TITLE
IE doesn't contain Max|Min _SAFE_INTEGER values.

### PR DESCRIPTION
**Pull request by sgtwilko**
This causes the bbox function to return NaN/undefined, fixes Pomax/bezierjs#79.

### CODE REVIEW

**Comment by Pomax** [comment]
Which version of IE are you looking at? (mostly because Microsoft's approach to version support has changed over the years and only IE11 and Edge are now officially supported).

**Comment by sgtwilko** [comment]
Hi @Pomax,

I realise you've merged this now, but to answer your question;
I found these were missing in IE11 on Windows 10, so presumably, they are missing in all prior versions.  It seems to be supported in Edge.

**Comment by Pomax** [comment]
It's definitely supported in Edge, and if you're on Windows 10, being on IE11 is "being on an outdated browser", IE11 is still supported mainly for enterprise setups with Windows 7, but Microsoft has changed its policy to only support the most-recent-supported-browser for each OS, so if you're still using IE on a Windows after 7, you're (a) on a browser that doesn't support the internet and (b) a browser that is not going to get the security support you want it to get.

**Comment by sgtwilko** [comment]
Hi @Pomax,

The policy is that they only support the most recent version of _Internet Explorer_ for an operating system.  They don't seem to count Edge as a version of Internet Explorer.

[This page](https://support.microsoft.com/en-gb/help/17454/lifecycle-faq-internet-explorer) clarifies that:

> Internet Explorer is a component of the Windows operating system and follows the Lifecycle Policy for the product on which it is installed. A component is defined as a set of files or features that are included with a Microsoft product, whether it is shipped with the product, included in a product service pack or update, or later made available as a web download for the product.

additionally:
> Internet Explorer 11 is the last major version of Internet Explorer. Internet Explorer 11 will continue receiving security updates and technical support for the lifecycle of the version of Windows on which it is installed.

Therefore, whilst it's subjective to say if it is outdated, we can definitively state that it will still get the security support for many years to come.

They do recommend Edge for Win10 users, but IE11 is still fully supported as it is the most recent version of IE on Windows 10, 8.1, 8 and 7.

Interestingly, Internet Explorer 10 is still fully supported due to Windows Server 2012 still being in Mainline support until 2018 and extended support until 2023.

Having said all that, I don't use it (I'm a Chrome and Firefox person), but that doesn't stop the people who use our websites from still using it! 😄

**Comment by Pomax** [comment]
Only for Windows Server 2012 users, though, which is a genuinely irrelevant number of modern-site-browsing users =)

Good point about the IE nomenclature though.

**Pull request merged**
